import random

def obter_frase_aleatoria():
    lista_de_frases = [
        "Interessante!",
    "Diga-me mais.",
    "Como posso ajudar você?",
    "Isso é fascinante!",
    "Conte-me mais sobre isso.",
    "Estou curioso para saber mais!",
    "Isso me intriga.",
    "Incrível!",
    "Isso faz todo o sentido.",
    "Que interessante!",
    "Estou aqui para ajudar.",
    "Você já pensou nisso antes?",
    "Eu nunca teria imaginado!",
    "Eu adoraria ouvir mais.",
    "Você tem uma perspectiva única.",
    "Que ponto de vista interessante!",
    "Estou impressionado!",
    "Estou aqui para responder às suas perguntas.",
    "Isso despertou meu interesse!",
    "Você tem alguma pergunta específica?",
    "Pode me contar mais detalhes?",
    "Eu realmente aprecio suas ideias.",
    "Posso te ajudar de alguma outra forma?",
    "Estou sempre pronto para aprender mais.",
    "Você sempre tem pensamentos interessantes.",
    "Isso é algo que muitas pessoas não sabem.",
    "Fascinante! Conte-me mais.",
    "Eu nunca considerei isso antes.",
    "Você tem uma mente brilhante!",
    "Gostaria de saber mais sobre isso.",
    "Você tem alguma dúvida em particular?",
    "Isso me deixa intrigado!",
    "Continue, estou ouvindo!",
    "Parece promissor!",
    "Estou aqui para ajudar no que precisar.",
    "Você já explorou outras ideias relacionadas?",
    "Que abordagem interessante!",
    "Adoraria ouvir mais sobre sua perspectiva.",
    "Você tem uma abordagem única para isso.",
    "Suas ideias são sempre bem-vindas!",
    "Estou aqui para te ajudar a explorar isso.",
    "Eu sempre gosto de aprender com os outros.",
    "Você me pegou de surpresa!",
    "Que pensamento original!",
    "Suas ideias são inovadoras.",
    "Estou empolgado para saber mais.",
    "Isso realmente me fez pensar.",
    "Você tem uma maneira única de ver as coisas.",
    "Eu nunca vi isso dessa forma antes.",
    "Você é muito criativo!",
    "Estou ansioso para ouvir mais sobre isso.",
    "Você sempre tem algo interessante para compartilhar.",
    "Isso me deixa curioso!",
    "Você já discutiu isso com outras pessoas?",
    "Estou aberto a ouvir suas opiniões.",
    "Eu admiro sua abordagem para isso.",
    "Você tem uma mente perspicaz!",
    "Essa é uma pergunta intrigante!",
    "Suas ideias são sempre estimulantes.",
    "Estou aqui para trocar ideias com você.",
    "Gostaria de explorar isso mais a fundo.",
    "Você tem alguma sugestão para resolver isso?",
    "Estou aqui para ajudar a resolver problemas.",
    "Você tem uma visão única do assunto.",
    "Posso te ajudar a encontrar mais informações?",
    "Sua perspicácia é notável!",
    "Estou pronto para ouvir mais.",
    "Que conceito interessante!",
    "Você já pensou em publicar suas ideias?",
    "Adoraria saber mais sobre sua experiência.",
    "Suas observações são muito valiosas.",
    "Estou aqui para ajudar no que precisar.",
    "Sua criatividade é inspiradora!",
    "Você tem uma abordagem única para isso.",
    "Estou ansioso para ouvir mais.",
    "Isso realmente me fez refletir.",
    "Você tem uma perspectiva única.",
    "Eu nunca teria pensado nisso.",
    "Suas ideias são sempre bem-vindas!",
    "Estou pronto para explorar isso mais a fundo.",
    "Você tem uma mente muito perspicaz!",
    "Isso é muito intrigante!",
    "Eu realmente aprecio suas ideias.",
    "Estou aqui para ajudar no que precisar.",
    "Que ponto de vista fascinante!",
    "Isso é algo digno de consideração.",
    "Você sempre tem algo interessante para compartilhar.",
    "Estou ansioso para ouvir mais.",
    "Sua abordagem é única e refrescante.",
    "Gostaria de ouvir mais detalhes.",
    "Isso é algo que vale a pena explorar.",
    "Sua criatividade é verdadeiramente excepcional.",
    "Estou pronto para ajudar no que for preciso.",
    "Você tem uma abordagem muito original.",
    "Eu adoraria saber mais sobre isso.",
    "Suas ideias sempre provocam reflexão.",
    "Que abordagem única para o problema!",
    "Estou aqui para ajudar no que precisar.",
    "Você sempre traz uma perspectiva única.",
    "Sua criatividade é verdadeiramente inspiradora.",
    "Estou ansioso para ouvir mais.",
    "Você tem uma maneira única de pensar.",
    "Que conceito fascinante!",
    "Isso realmente me fez considerar novas perspectivas.",
    "Estou pronto para discutir isso mais a fundo.",
    "Suas observações são muito perspicazes.",
    "Estou aqui para ajudar no que precisar.",
    "Sua visão única é muito inspiradora.",
    "Você sempre tem algo interessante para compartilhar.",
    "Estou ansioso para ouvir mais.",
    "Sua abordagem é refrescante e original.",
    "Gostaria de explorar isso mais a fundo.",
    "Suas ideias são sempre dignas de reflexão.",
    "Estou pronto para ajudar no que precisar."
]
    frase_aleatoria = random.choice(lista_de_frases)
    return frase_aleatoria

# palavras_chave.py

def obter_palavras_chave():
    return [
        "python", "chatbot", "criar", "texto", "programação", "inteligência artificial",
        "aprendizado de máquina", "linguagem natural", "desenvolvimento", "projetos",
        "tecnologia", "inovação", "computação", "código", "algoritmo", "data science",
        "web", "api", "interface", "usuário", "front-end", "back-end", "mobile", "segurança",
        "dados", "analítica", "cloud computing", "IoT", "automatização", "ciência da computação",
        "robótica", "automação", "blockchain", "redes", "sistemas distribuídos", "devops",
        "web scraping", "machine learning", "deep learning", "neural networks", "big data",
        "analytics", "java", "python", "javascript", "c++", "html", "css", "react", "angular",
        "vue", "django", "flask", "node.js", "docker", "kubernetes", "git", "github", "sql",
        "mongodb", "postgresql", "nosql", "agile", "scrum", "kanban", "design thinking",
        "usabilidade", "user experience", "responsive design", "mobile-first", "teste A/B",
        "prototipagem", "algoritmos genéticos", "processamento de linguagem natural",
        "visão computacional", "realidade aumentada", "realidade virtual", "blockchain",
        "criptomoedas", "smart contracts", "cibersegurança", "firewall", "hacking ético",
        "computação quântica", "sistemas operacionais", "linux", "windows", "macOS", "shell scripting",
        "cloud", "aws", "azure", "google cloud", "firebase", "serverless", "microservices", "API REST",
        "GraphQL", "websockets", "internet das coisas", "dispositivos inteligentes", "automóveis autônomos",
        "indústria 4.0", "realidade aumentada", "realidade virtual", "big data", "data lakes",
        "data warehouses", "ETL", "data mining", "business intelligence", "dashboards", "chatbots",
        "assistente virtual", "voice recognition", "speech-to-text", "nlp", "natural language processing",
        "reconhecimento de padrões", "machine vision", "reinforcement learning", "processamento de sinais",
        "edge computing", "fog computing", "elasticidade", "escalabilidade", "integração contínua",
        "entrega contínua", "monitoramento", "log analytics", "incident response", "backup",
        "recuperação de desastres", "troubleshooting", "machine translation", "tradução automática",
        "análise de sentimentos", "processamento de imagem", "processamento de áudio", "computação gráfica",
        "realidade mista", "edge computing", "fog computing", "realidade mista", "blockchain",
        "contratos inteligentes", "IoT", "internet das coisas", "indústria 4.0", "cidades inteligentes",
        "energia renovável", "sustentabilidade", "inteligência de enxame", "drones", "tecnologia vestível",
        "dispositivos biométricos", "impressão 3D", "blockchain na saúde", "telemedicina", "blockchain nas finanças",
        "open source", "software livre", "licenças de código aberto", "crowdsourcing", "gamificação",
        "inteligência artificial ética", "privacidade de dados", "ética na tecnologia", "inteligência artificial explicável",
        "diversidade e inclusão na tecnologia", "tecnologia na educação", "ensino à distância", "educação online",
        "tecnologia assistiva", "inclusão digital", "tecnologia na cultura", "música e tecnologia", "arte generativa",
        "realidade virtual na arte", "tecnologia na moda", "tecnologia na arquitetura", "tecnologia na gastronomia",
        "tecnologia na agricultura", "agrotech", "blockchain na cadeia de suprimentos", "tecnologia espacial",
        "exploração espacial", "turismo espacial", "colonização de Marte", "inteligência artificial na medicina",
        "robótica cirúrgica", "telecirurgia", "impressão 3D em medicina", "biotecnologia", "nanotecnologia",
        "internet das coisas na saúde", "saúde digital", "blockchain na saúde", "tecnologia na prevenção de pandemias",
        "tecnologia e mudanças climáticas", "energias renováveis", "tecnologia de captura de carbono", "inovações sustentáveis"
    ]


# correcoes.py

def obter_correcoes():
    return {
        "pyhton": "python", "criarrr": "criar", "textoo": "texto",
        "programacão": "programação", "chabot": "chatbot", "criarr": "criar",
        "texo": "texto", "pythom": "python", "criacao": "criar", "testo": "texto",
        "pytho": "python", "ciar": "criar", "crir": "criar", "programacao": "programação",
        "código": "código", "programaccao": "programação", "linguagem": "linguagem",
        "natural": "natural", "desenvolvimento": "desenvolvimento", "projetos": "projetos",
        "tecnologa": "tecnologia", "inovacao": "inovação", "computacao": "computação",
        "codgo": "código", "algoritmo": "algoritmo", "dados": "dados", "analitica": "analítica",
        "web": "web", "api": "api", "interface": "interface", "usario": "usuário",
        "frontend": "front-end", "backend": "back-end", "mobile": "mobile", "seguranca": "segurança",
        "dados": "dados", "analitica": "analítica", "cloud": "cloud", "IoT": "IoT",
        "automacao": "automatização", "ciencia": "ciência", "robotica": "robótica",
        "automacao": "automação", "blockchain": "blockchain", "redes": "redes",
        "sistemas": "sistemas", "distribuidos": "distribuídos", "devops": "devops",
        "webscraping": "web scraping", "machinelearning": "machine learning",
        "deeplearning": "deep learning", "neuralnetworks": "neural networks",
        "bigdata": "big data", "analytics": "analytics", "java": "java",
        "python": "python", "javascript": "javascript", "cpp": "c++", "html": "html",
        "css": "css", "react": "react", "angular": "angular", "vue": "vue",
        "django": "django", "flask": "flask", "nodejs": "node.js", "docker": "docker",
        "kubernetes": "kubernetes", "git": "git", "github": "github", "sql": "sql",
        "mongodb": "mongodb", "postgresql": "postgresql", "nosql": "nosql",
        "agile": "agile", "scrum": "scrum", "kanban": "kanban", "designthinking": "design thinking",
        "usabilidade": "usabilidade", "userexperience": "user experience", "responsivedesign": "responsive design",
        "mobilefirst": "mobile-first", "testea/b": "teste A/B", "prototipagem": "prototipagem",
        "algoritmosgeneticos": "algoritmos genéticos", "processamentodelinguagemnatural": "processamento de linguagem natural",
        "visaocomputacional": "visão computacional", "realidadeaumentada": "realidade aumentada",
        "realidadevirtual": "realidade virtual", "blockchain": "blockchain", "criptomoedas": "criptomoedas",
        "contratosinteligentes": "contratos inteligentes", "ciberseguranca": "cibersegurança",
        "firewall": "firewall", "hackingetico": "hacking ético", "computacaoquantica": "computação quântica",
        "sistemasoperacionais": "sistemas operacionais", "linux": "linux", "windows": "windows",
        "macOS": "macOS", "shellscripting": "shell scripting", "cloud": "cloud",
        "aws": "aws", "azure": "azure", "googlecloud": "google cloud", "firebase": "firebase",
        "serverless": "serverless", "microservices": "microservices", "APIREST": "API REST",
        "GraphQL": "GraphQL", "websockets": "websockets", "internetdascoisas": "internet das coisas",
        "dispositivosinteligentes": "dispositivos inteligentes", "automoveisautonomos": "automóveis autônomos",
        "industria4.0": "indústria 4.0", "realidadeaumentada": "realidade aumentada",
        "realidadevirtual": "realidade virtual", "bigdata": "big data", "datalakes": "data lakes",
        "datawarehouses": "data warehouses", "ETL": "ETL", "datamining": "data mining",
        "businessintelligence": "business intelligence", "dashboards": "dashboards", "chatbots": "chatbots",
        "assistentevirtual": "assistente virtual", "voicerecognition": "voice recognition",
        "speech-to-text": "speech-to-text", "nlp": "nlp", "naturallanguageprocessing": "natural language processing",
        "reconhecimentodepadroes": "reconhecimento de padrões", "machinevision": "machine vision",
        "reinforcementlearning": "reinforcement learning", "processamentodesinais": "processamento de sinais",
        "edgecomputing": "edge computing", "fogcomputing": "fog computing", "elasticidade": "elasticidade",
        "escalabilidade": "escalabilidade", "integracaocontinua": "integração contínua", "entregacontinua": "entrega contínua",
        "monitoramento": "monitoramento", "loganalytics": "log analytics", "incidentresponse": "incident response",
        "backup": "backup", "recuperacaodedesastres": "recuperação de desastres", "troubleshooting": "troubleshooting",
        "machinetranslation": "machine translation", "traducaoautomatica": "tradução automática",
        "analisedesentimentos": "análise de sentimentos", "processamentodeimagem": "processamento de imagem",
        "processamentodeaudio": "processamento de áudio", "computacaografica": "computação gráfica",
        "realidademista": "realidade mista", "edgecomputing": "edge computing", "fogcomputing": "fog computing",
        "realidademista": "realidade mista", "blockchain": "blockchain", "contratosinteligentes": "contratos inteligentes",
        "IoT": "IoT", "internetdascoisas": "internet das coisas", "industria4.0": "indústria 4.0",
        "cidadesinteligentes": "cidades inteligentes", "energiarenovavel": "energia renovável",
        "sustentabilidade": "sustentabilidade", "inteligenciadeenxame": "inteligência de enxame", "drones": "drones",
        "tecnologiavestivel": "tecnologia vestível", "dispositivosbiometricos": "dispositivos biométricos",
        "impressao3D": "impressão 3D", "blockchainnasaude": "blockchain na saúde", "telemedicina": "telemedicina",
        "blockchainnasfinancas": "blockchain nas finanças", "opensource": "open source", "softwarelivre": "software livre",
        "licencasdecodigoaberto": "licenças de código aberto", "crowdsourcing": "crowdsourcing", "gamificacao": "gamificação",
        "inteligenciaartificialetica": "inteligência artificial ética", "privacidadedados": "privacidade de dados",
        "eticanatecnologia": "ética na tecnologia", "inteligenciaartificiaalexplicavel": "inteligência artificial explicável",
        "diversidadeeinclusaonatecnologia": "diversidade e inclusão na tecnologia", "tecnologianaeducacao": "tecnologia na educação",
        "ensinoadistancia": "ensino à distância", "educacaoonline": "educação online", "tecnologiaassistiva": "tecnologia assistiva",
        "inclusaodigital": "inclusão digital", "tecnologianacultura": "tecnologia na cultura", "musicatecnologia": "música e tecnologia",
        "artegenerativa": "arte generativa", "realidadevirtualnaarte": "realidade virtual na arte", "tecnologiana moda": "tecnologia na moda",
        "tecnologianaarquitetura": "tecnologia na arquitetura", "tecnologianagastronomia": "tecnologia na gastronomia",
        "tecnologianaagricultura": "tecnologia na agricultura", "agrotech": "agrotech", "blockchainnacadeiadesuprimentos": "blockchain na cadeia de suprimentos",
        "tecnologiaespacial": "tecnologia espacial", "exploracaoespacial": "exploração espacial", "turismoespacial": "turismo espacial",
        "colonizacaodemarte": "colonização de Marte", "inteligenciaartificialnamedicina": "inteligência artificial na medicina",
        "roboticacirurgica": "robótica cirúrgica", "telecirurgia": "telecirurgia", "impressao3Demedicina": "impressão 3D em medicina",
        "biotecnologia": "biotecnologia", "nanotecnologia": "nanotecnologia", "internetdascoisasnasaude": "internet das coisas na saúde",
        "saudedigital": "saúde digital", "blockchainnasaude": "blockchain na saúde", "tecnologiaprevencaopandemias": "tecnologia na prevenção de pandemias",
        "tecnologiaemudancasclimaticas": "tecnologia e mudanças climáticas", "energiasrenovaveis": "energias renováveis",
        "tecnologiacapturadecarbono": "tecnologia de captura de carbono", "inovacoessustentaveis": "inovações sustentáveis"
    }


